# Generated by Django 5.0.2 on 2024-05-07 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_abstractloggableaction_assigneechange_workflowpush_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowpush',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assigneechange',
            name='new_assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AlterField(
            model_name='workflowpush',
            name='from_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes_from', to='api.workflowstage'),
        ),
        migrations.AlterField(
            model_name='workflowpush',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes_to', to='api.workflowstage'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
