# Generated by Django 5.0.2 on 2024-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
