# Generated by Django 5.0.2 on 2024-05-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_linked_tasks_task_parent_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowpush',
            name='from_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pushes_from', to='api.workflowstage'),
        ),
        migrations.AlterField(
            model_name='workflowpush',
            name='to_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pushes_to', to='api.workflowstage'),
        ),
    ]
