# Generated by Django 5.0.2 on 2024-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.JSONField(),
        ),
    ]
