# Generated by Django 5.0.2 on 2024-06-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_document_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenStateChange',
            fields=[
                ('abstractloggableaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.abstractloggableaction')),
                ('new_state', models.BooleanField()),
            ],
            bases=('api.abstractloggableaction',),
        ),
        migrations.AddField(
            model_name='abstractloggableaction',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
            preserve_default=False,
        ),
    ]
