# Generated by Django 5.0.2 on 2024-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_openstatechange_abstractloggableaction_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='settings',
            field=models.JSONField(default={'tag_coloring': {}, 'views': []}),
        ),
    ]
