# Generated by Django 5.0.2 on 2024-06-06 17:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_workspace_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='settings',
            field=models.JSONField(default=api.models.default_workspace_settings),
        ),
    ]
