# Generated by Django 5.0.2 on 2024-06-12 09:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_pfp_to),
        ),
    ]
