version: "3.7"
services:
  db_service:
    image: postgres:13.3
    hostname: ${DB_HOST}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    expose:
      - ${DB_PORT}
    networks:
      - main_network
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis_service:
    image: redis:latest
    restart: always
    hostname: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - ${REDIS_PORT}
    networks:
      - main_network
    volumes:
      - redisdata:/root/redis
      - redisconf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: 16

  api_server:
    build: backend
    hostname: ${API_HOST}
    environment:
      SERVER_ADDRESS: "0.0.0.0:${API_PORT}"
      PG_NAME: ${DB_NAME}
      PG_USER: ${DB_USER}
      PG_PASS: ${DB_PASS}
      PG_PORT: ${DB_PORT}
      PG_HOST: ${DB_HOST}
      USE_DB: "production"
      REDIS_PASSWORD: ${REDIS_PASS}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "${API_PORT}:${API_PORT}"
    expose:
      - ${API_PORT}
    networks:
      - main_network
    depends_on:
      db_service:
        condition: service_healthy
    links:
      - db_service
      - redis_service

  frontend_service:
    build: frontend
    environment:
      API_BASE_URL: "${API_HOST}:${API_PORT}/api/"
    ports:
      - "80:3000"
    expose:
      - "80"
    networks:
      - main_network
    depends_on:
      api_server:
        condition: service_started
    links:
      - api_server


networks:
  main_network:
    driver: bridge


volumes:
  pgdata:
  redisdata:
  redisconf:
