version: "3.7"
services:
  frontend_service:
    environment:
      API_BASE_URL: "localhost:8080"
      API_WS_URL: "ws://localhost:8080/ws/"

  nginx_service:
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
